"""Export shared preview/C++ visual data. No builds, image edits, or game execution."""
from pathlib import Path
import json, struct
P=Path(__file__).resolve().parent
assets=[]; clips=[]
def asset(path):
    b=(P/path).read_bytes(); assert b[:8]==b'\x89PNG\r\n\x1a\n'
    w,h=struct.unpack('>II',b[16:24]); assets.append(dict(path=path,width=w,height=h)); return len(assets)-1
def sprite(a,rect,dx,dy,s,blend=0):
    x,y,w,h=rect; assert x>=0 and y>=0 and x+w<=assets[a]['width'] and y+h<=assets[a]['height']
    return dict(asset=a,rect=rect,offset=[dx,dy],scale=s,blend=blend)
def frame(ms,sp): return dict(ms=ms,sprite=sp)
def add(id,name,job,body,fx=None,start=0,anchors=None):
    clips.append(dict(id=id,name=name,profession=job,body=body,effect=fx or [],effectStart=start,anchors=anchors or [[0,0]]*len(body),duration=max(sum(f['ms'] for f in body),start+sum(f['ms'] for f in fx or []))))
kw=asset('SmallKnight/walk-transparent-v1.png'); ka=asset('SmallKnight/attacks-transparent-v2.png'); kf=asset('SmallKnight/effects-transparent-v2.png')
mw=asset('SmallMage/walk-transparent-v2.png')
ma=[asset('SmallMage/'+p) for p in ['left-jab-drawn-v2.png','mana-blade-motion-v1.png','double-palm-motion-v2.png']]
mf=[asset('Attack/Mage/mage-melee-effects-v1.png'),asset('SmallMage/mana-blade-v1.png'),asset('Attack/Mage/mage-burst-b-v2.png')]
# Knight buckle centers vary within the source cells. Keep the first frame's
# body-to-foot offset, removing horizontal sheet drift without changing poses.
knight_walk_pivots=[192,191,177.5,160,195,189,176.5,158]
for job,a,s,bases in [(1,kw,.45,[453,388]),(0,mw,.42,[456,424])]:
    pivots=knight_walk_pivots if job else [192]*8
    add(('knight' if job else 'mage')+'-walk','이동',job,[frame(90,sprite(a,[i%4*384,i//4*512,384,512],-pivots[i]*s,-bases[i//4]*s,s)) for i in range(8)])
poses=[0,1,2,3,3,4,4,4,5,0]; times=[150,130,35,35,45,45,40,40,130,160]; rows=[0,341,650,1024]
for r,name in enumerate(['방패 밀치기','가로 베기','내려베기']):
    body=[];fx=[];anchors=[]; s=.64; es=[.78,.92,.8][r]
    edges=[0,256,512,768,1034 if r==1 else 1024,1280,1536]
    for f,t in zip(poses,times):
        x=edges[f]; body.append(frame(t,sprite(ka,[x,rows[r],edges[f+1]-x,rows[r+1]-rows[r]],-128*s+(x-f*256)*s,-([324,628,941][r]-rows[r])*s,s)))
        anchors.append([0,([939,938,938,945,949,939][f]-941)*s if r==2 else 0])
    edges=[0,256,512,779 if r==1 else 768,1024,1280,1536]
    for e,t in enumerate(times[2:8]):
        x=edges[e]; dx=[341,290,323][r]-260-[128,128,170][r]*es+(x-e*256)*es
        dy=-([945,945,964,959,952,944][e]-rows[r])*es if r==2 else [247,266,300][r]-300-[190,180,292][r]*es
        fx.append(frame(t,sprite(kf,[x,rows[r],edges[e+1]-x,rows[r+1]-rows[r]],dx,dy,es)))
    add('knight-'+str(r+1),name,1,body,fx,280,anchors)
seqs=[[0,1,2,3,5,6,7],list(range(8)),list(range(8))]
times=[[140,130,45,40,45,75,150],[140,110,90,50,60,65,90,150],[140,130,70,50,90,80,100,150]]
et=[[40,40,45,45,55,70],[30,30,40,40,50,65],[80,75,45,65,85,90,85,80]]
for r,name in enumerate(['왼손 정권지르기','마력칼날','양손 앞으로 뻗기']):
    body=[frame(t,sprite(ma[r],[f%4*384,f//4*480,384,480],-210*.42,-456*.42,.42)) for f,t in zip(seqs[r],times[r])]
    anchors=[]
    for f in seqs[r]:
        p=[340,290] if r==0 else [348,290] if r==2 else [[125,345],[105,295],[100,295],[235,315],[295,295],[320,295]][min(f,5)]
        anchors.append([(p[0]-210)*.42+(20 if r==0 else 0),(p[1]-456)*.42-(5 if r==0 else 0)])
    fx=[]
    for e,t in enumerate(et[r]):
        if r==0: rect=[e*256,0,256,341];root=[128,200];s=.55
        elif r==1:rect=[e%3*512,e//3*512,512,512];root=[[196,150,105,104,95,112][e],[262,260,260,256,255,264][e]];s=.55
        else:rect=[e%4*384,e//4*512,384,512];root=[[98,94,96,70,88,76,86,74][e],232 if e//4 else 262];s=.65
        fx.append(frame(t/[1,.8,1.2][r],sprite(mf[r],rect,-root[0]*s,-root[1]*s,s,0 if r==1 else 1)))
    add('mage-'+str(r+1),name,0,body,fx,[315,340,340][r],anchors)
data=dict(version=1,origin='feet; x right, y down; milliseconds',assets=assets,clips=clips)
(P/'combat-visuals.json').write_text(json.dumps(data,ensure_ascii=False,indent=2),encoding='utf-8')
(P/'combat-visuals.js').write_text('globalThis.COMBAT_VISUALS = '+json.dumps(data,ensure_ascii=False)+';\n',encoding='utf-8')
# C++ tables use the exact same data as the browser; no JSON parser needed in game.
fnum=lambda n:format(n,'.9f')+'f'
out=['#pragma once','// Generated by Assets/Characters/export-combat-visuals.py. Do not edit.','namespace CombatVisuals {',
'struct Asset { const wchar_t* path; int width,height; };',
'struct Sprite { int asset,x,y,w,h; float dx,dy,scale; int blend; }; // blend 0 alpha, 1 additive',
'struct Frame { float ms; Sprite sprite; };',
'struct Anchor { float x,y; };',
'struct Clip { const char* id; int profession; const Frame* body; int bodyCount; const Frame* effect; int effectCount; const Anchor* anchors; float effectStart,duration; };',
'static const Asset assets[] = {']
for a in assets:out.append('{L"'+a['path']+'",'+str(a['width'])+','+str(a['height'])+'},')
out+=['};']
for i,c in enumerate(clips):
    for key in ['body','effect']:
        if not c[key]:continue
        out.append('static const Frame '+key+str(i)+'[] = {')
        for f in c[key]:
            s=f['sprite'];out.append('{'+fnum(f['ms'])+',{'+','.join(map(str,[s['asset']]+s['rect']))+','+','.join(map(fnum,s['offset']+[s['scale']]))+','+str(s['blend'])+'}},')
        out.append('};')
    out.append('static const Anchor anchors'+str(i)+'[] = {'+','.join('{'+','.join(map(fnum,a))+'}' for a in c['anchors'])+'};')
out.append('static const Clip clips[] = {')
for i,c in enumerate(clips):out.append('{"'+c['id']+'",'+str(c['profession'])+',body'+str(i)+','+str(len(c['body']))+','+('effect'+str(i) if c['effect'] else 'nullptr')+','+str(len(c['effect']))+',anchors'+str(i)+','+fnum(c['effectStart'])+','+fnum(c['duration'])+'},')
out+=['};','static const int assetCount = sizeof(assets)/sizeof(assets[0]);','static const int clipCount = sizeof(clips)/sizeof(clips[0]);',
'inline int FrameAt(const Frame* frames,int count,float time) { if(time<0)return -1; for(int i=0;i<count;++i){if(time<frames[i].ms)return i;time-=frames[i].ms;}return -1; }',
'// Returns up to two draw commands in foot-relative coordinates. Caller owns flip, scale, GL blending.',
'inline int Sample(const Clip& clip,float ms,Sprite* output) { if(!output || ms<0 || ms>=clip.duration)return 0; int b=FrameAt(clip.body,clip.bodyCount,ms); if(b<0)b=clip.bodyCount-1; output[0]=clip.body[b].sprite; int e=FrameAt(clip.effect,clip.effectCount,ms-clip.effectStart); if(e<0)return 1; output[1]=clip.effect[e].sprite;output[1].dx+=clip.anchors[b].x;output[1].dy+=clip.anchors[b].y;return 2; }','}']
(P.parent.parent/'CombatVisualData.h').write_text('\n'.join(out)+'\n',encoding='utf-8')
project=['<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">','<ItemGroup>']
for a in assets:
    path=a['path'].replace('/','\\')
    project.append('<PreparedCombatAsset Include="$(MSBuildThisFileDirectory)Assets\\Characters\\'+path+'"><RelativePath>'+path+'</RelativePath></PreparedCombatAsset>')
project+=['</ItemGroup>','<Target Name="CopyPreparedCombatAssets" AfterTargets="Build">','<Copy SourceFiles="@(PreparedCombatAsset)" DestinationFiles="@(PreparedCombatAsset->\'$(TargetDir)Assets\\Characters\\%(RelativePath)\')" SkipUnchangedFiles="true" />','</Target>','</Project>']
(P.parent.parent/'PreparedCombatAssets.targets').write_text('\n'.join(project),encoding='utf-8')
assert len(clips)==8 and all(len(c['anchors'])==len(c['body']) for c in clips)
print(f'Exported {len(assets)} assets / {len(clips)} clips; paths and source rectangles checked. No build/run.')
